version: "3"

services:
  gateway:
    image: "restaurant/gateway"
    ports:
      - 9500:8080
    depends_on:
      - ${MENU_SERVICE}
      - ${KITCHEN_SERVICE}
      - ${DINING_SERVICE}
    networks:
      - spring-restaurant-network

networks:
  spring-restaurant-network:
    driver: bridge
