version: "3"

services:
  kitchen-service:
    image: "restaurant/kitchen-service"
    ports:
      - 3002:8080
    depends_on:
      - mongo_db_kitchen
    environment:
      - DINING_WITH_PORT=${DINING_SERVICE}:8080
    networks:
      - spring-restaurant-network
  mongo_db_kitchen:
    image: ${MONGO_IMAGE}
    ports:
      - 27019:27017
    networks:
      - spring-restaurant-network

networks:
  spring-restaurant-network:
    driver: bridge
